window.SEED_PRODUCTS = [
  {
    id: 1,
    sku: "ATL-UNI-001",
    name: "Camiseta táctica Dry-Fit",
    description:
      "Camiseta de servicio en tejido Dry-Fit de secado rápido. Corte atlético que no estorba bajo chaleco o placa. Costuras planas en hombros y costados para reducir rozaduras en jornadas largas. Cuello redondo reforzado que no se deforma con el lavado.",
    category: "uniformes",
    priceSoles: 89,
    stock: 24,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Olivo", hex: "#4B5320" },
      { name: "Negro", hex: "#1A1A1A" },
      { name: "Coyote", hex: "#9A7B4F" },
    ],
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Poliéster Dry-Fit 160 g/m²",
    weightG: 180,
    features: ["Secado rápido", "Anti-olor", "Costuras planas", "Cuello reforzado"],
    specs: { Uso: "Instrucción y servicio diario", Corte: "Atlético", Cuidado: "Lavado a 30 °C" },
    featured: true,
  },
  {
    id: 2,
    sku: "ATL-UNI-002",
    name: "Pantalón cargo Ripstop 6 bolsillos",
    description:
      "Pantalón de faena en ripstop polialgodón. Seis bolsillos de carga con fuelle, rodillas reforzadas y pretina con elástico interior para mantener el pantalón en su sitio con cinturón rigger. Tela que no se abre en desgarro y resiste rozadura de monte.",
    category: "uniformes",
    priceSoles: 189,
    stock: 18,
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    colors: [
      { name: "Olivo", hex: "#4B5320" },
      { name: "Khaki", hex: "#A3926B" },
      { name: "Negro", hex: "#1A1A1A" },
    ],
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Ripstop 65% poliéster / 35% algodón",
    weightG: 520,
    features: ["6 bolsillos de carga", "Rodilla reforzada", "Ripstop anti-desgarro", "Pretina con elástico"],
    specs: { Uso: "Faena y patrulla", Cierre: "Botón y bragueta", Cuidado: "Lavado industrial suave" },
    featured: true,
  },
  {
    id: 3,
    sku: "ATL-CAL-001",
    name: 'Bota de combate 8" cuero y cordura',
    description:
      "Bota de caña 8 pulgadas con capellada de cuero full-grain y cordura 1000D. Suela de goma de alta tracción, plantilla amortiguada y puntera reforzada. Pensada para marcha con equipo y terreno mixto. Cremallera lateral con fuelle para calzar rápido sin perder sello.",
    category: "calzado",
    priceSoles: 349,
    stock: 12,
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    colors: [
      { name: "Negro", hex: "#1A1A1A" },
      { name: "Coyote", hex: "#9A7B4F" },
    ],
    images: [
      "https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1539185441755-769473a23584?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Cuero full-grain y Cordura 1000D",
    weightG: 1480,
    features: ["Caña 8 pulgadas", "Cremallera lateral", "Suela de alta tracción", "Puntera reforzada"],
    specs: { Altura: "8 pulgadas", Suela: "Goma vibram-style", Plantilla: "EVA extraíble" },
    featured: true,
  },
  {
    id: 4,
    sku: "ATL-CHA-001",
    name: "Chaleco táctico MOLLE",
    description:
      "Chaleco portaplacas ligero con trama MOLLE en pecho, espalda y costados. Ajuste de hombros y cinchas laterales. Compatible con placas blandas o rígidas de talla estándar. Malla interior para ventilación. Pensado para instrucción, seguridad y servicio, no como disfraz.",
    category: "chalecos",
    priceSoles: 279,
    stock: 10,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Negro", hex: "#1A1A1A" },
      { name: "Olivo", hex: "#4B5320" },
      { name: "Coyote", hex: "#9A7B4F" },
    ],
    images: [
      "https://images.unsplash.com/photo-1544022613-e87caecea06c?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Nylon 500D con malla 3D",
    weightG: 890,
    features: ["Trama MOLLE completa", "Ajuste de hombros y costado", "Compatible con placa estándar", "Malla interior ventilada"],
    specs: { Placas: "SAPI / ESAPI talla M-L", "Peso vacío": "890 g", Cierre: "Cinchas laterales" },
    featured: true,
  },
  {
    id: 5,
    sku: "ATL-MOC-001",
    name: "Mochila de asalto 40 L",
    description:
      "Mochila de 40 litros con compartimento principal de boca amplia, bolsillo de hidratación, correas de compresión y panel MOLLE frontal. Espalda acolchada con canal de aire. Cinturón lumbar desmontable. Sirve para salida de 24–48 h o transporte de equipo de instrucción.",
    category: "mochilas",
    priceSoles: 229,
    stock: 14,
    sizes: ["Única"],
    colors: [
      { name: "Olivo", hex: "#4B5320" },
      { name: "Negro", hex: "#1A1A1A" },
      { name: "Coyote", hex: "#9A7B4F" },
    ],
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Nylon 600D ripstop",
    weightG: 1100,
    features: ["40 litros", "Panel MOLLE", "Hidratación 3 L", "Cinturón lumbar desmontable"],
    specs: { Capacidad: "40 L", Hidratación: "Funda para vejiga 3 L", Dimensiones: "54 × 32 × 22 cm" },
    featured: false,
  },
  {
    id: 6,
    sku: "ATL-ACC-001",
    name: "Gorra operator con velcro",
    description:
      "Gorra de perfil bajo con visera curva, ajuste de velcro posterior y panel de velcro frontal para parche. Tejido ripstop ligero, interior con cinta anti-sudor. No deforma con el sol ni el lavado a mano.",
    category: "accesorios",
    priceSoles: 45,
    stock: 30,
    sizes: ["S/M", "L/XL"],
    colors: [
      { name: "Negro", hex: "#1A1A1A" },
      { name: "Olivo", hex: "#4B5320" },
      { name: "Arena", hex: "#C2A878" },
    ],
    images: [
      "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Ripstop poliéster",
    weightG: 85,
    features: ["Panel velcro para parche", "Ajuste posterior", "Cinta anti-sudor", "Perfil bajo"],
    specs: { Perfil: "Bajo", Visera: "Curva", Parche: "Velcro 8 × 5 cm" },
    featured: false,
  },
  {
    id: 7,
    sku: "ATL-ABR-001",
    name: "Chaqueta softshell cortaviento",
    description:
      "Softshell de tres capas: exterior elástico cortaviento, membrana transpirable y interior de micropolar. Capucha ajustable que entra bajo casco, axilas con cremallera de ventilación y bolsillos altos para usar con chaleco. Ideal para frío seco de sierra y viento en costa.",
    category: "abrigos",
    priceSoles: 259,
    stock: 8,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Negro", hex: "#1A1A1A" },
      { name: "Olivo", hex: "#4B5320" },
    ],
    images: [
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1544022613-e87caecea06c?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Softshell 3 capas, membrana TPU",
    weightG: 640,
    features: ["Cortaviento", "Capucha bajo casco", "Cremalleras de axila", "Bolsillos altos"],
    specs: { Clima: "Frío seco y viento", Capucha: "Ajustable, casco-compatible", Cuidado: "No usar suavizante" },
    featured: true,
  },
  {
    id: 8,
    sku: "ATL-ACC-002",
    name: "Guantes tácticos con nudillo",
    description:
      "Guantes de dedo completo con palma de cuero sintético antideslizante, nudillos termoplásticos y dorso transpirable. Dedo índice y pulgar táctiles para pantalla. Muñeca con velcro. Protección sin perder destreza para arma, volante o herramientas.",
    category: "accesorios",
    priceSoles: 69,
    stock: 20,
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Negro", hex: "#1A1A1A" },
      { name: "Olivo", hex: "#4B5320" },
    ],
    images: [
      "https://images.unsplash.com/photo-1588345921523-c2dcd7f38b0d?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Piel sintética, spandex y TPR",
    weightG: 120,
    features: ["Nudillo rígido", "Palma antideslizante", "Punta táctil", "Cierre de velcro"],
    specs: { Dedos: "Completos", Pantalla: "Índice y pulgar táctiles", Par: "Incluye ambos" },
    featured: false,
  },
  {
    id: 9,
    sku: "ATL-ACC-003",
    name: "Cinturón rigger 45 mm",
    description:
      "Cinturón de 45 mm en nylon de alta densidad con hebilla de doble barra. No tiene agujeros: se ajusta al milímetro y no afloja con el peso del equipo. Compatible con fundas y portaequipo de cintura. Largo recortable.",
    category: "accesorios",
    priceSoles: 55,
    stock: 22,
    sizes: ["Única"],
    colors: [
      { name: "Negro", hex: "#1A1A1A" },
      { name: "Coyote", hex: "#9A7B4F" },
      { name: "Olivo", hex: "#4B5320" },
    ],
    images: [
      "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Nylon 45 mm, hebilla acetal",
    weightG: 160,
    features: ["Ancho 45 mm", "Ajuste continuo", "Hebilla de doble barra", "Largo recortable"],
    specs: { Ancho: "45 mm", Largo: "Hasta 125 cm, recortable", Hebilla: "Acetal de doble barra" },
    featured: false,
  },
  {
    id: 10,
    sku: "ATL-ABR-002",
    name: "Poncho impermeable 3 en 1",
    description:
      "Poncho de nylon recubierto que cubre al usuario con mochila puesta. Se convierte en toldo ligero con las ojetes de esquina y, plegado, en capa de suelo. Costuras termoselladas. No es traje de lluvia de ciudad: está cortado para servicio a campo.",
    category: "abrigos",
    priceSoles: 119,
    stock: 16,
    sizes: ["Única"],
    colors: [
      { name: "Olivo", hex: "#4B5320" },
      { name: "Negro", hex: "#1A1A1A" },
    ],
    images: [
      "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Nylon 210T recubierto PU",
    weightG: 380,
    features: ["Impermeable", "Cubre mochila", "Ojetes para toldo", "Costuras termoselladas"],
    specs: { Modos: "Poncho, toldo, suelo", "Índice agua": "3000 mm", Empaque: "Bolsa incluida" },
    featured: false,
  },
  {
    id: 11,
    sku: "ATL-UNI-003",
    name: "Conjunto camuflaje selva",
    description:
      "Camisa y pantalón de camuflaje selva en ripstop. Camisa de manga larga con bolsillos de pecho, hombreras y puños ajustables. Pantalón con bolsillos cargo y pretina reforzada. Patrón de selva de alto contraste para monte húmedo. Se vende como conjunto.",
    category: "uniformes",
    priceSoles: 320,
    stock: 9,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Selva", hex: "#3D4A2F" }],
    images: [
      "https://images.unsplash.com/photo-1548449112-96a38a64381d?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1579912437766-7896df6d3cd3?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Ripstop polialgodón, estampado selva",
    weightG: 980,
    features: ["Conjunto camisa + pantalón", "Bolsillos de pecho y cargo", "Puños ajustables", "Ripstop"],
    specs: { Incluye: "Camisa y pantalón", Patrón: "Selva", Manga: "Larga, arremangable" },
    featured: true,
  },
  {
    id: 12,
    sku: "ATL-CAL-002",
    name: "Bota desierto transpirable",
    description:
      "Bota de caña media para clima cálido. Malla y gamuza en la capellada para ventilación, suela de goma que no se ablanda en asfalto caliente y plantilla extraíble. Menos peso que la bota de combate 8\". Indicada para costa y zonas áridas.",
    category: "calzado",
    priceSoles: 299,
    stock: 11,
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45", "46"],
    colors: [
      { name: "Arena", hex: "#C2A878" },
      { name: "Coyote", hex: "#9A7B4F" },
    ],
    images: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=900&q=80",
    ],
    material: "Gamuza, malla y suela de goma",
    weightG: 980,
    features: ["Caña media", "Capellada transpirable", "Suela resistente al calor", "Plantilla extraíble"],
    specs: { Altura: "6 pulgadas", Clima: "Cálido y árido", "Peso par": "980 g talla 42" },
    featured: false,
  },
];
